### ISSUE TITLE
where is the settings.py file?

### ISSUE THREAD

**Issue by riceluxs1t** [rice-apps/rice-bikes#21]

**Comment by caderitter** [comment]
mysite/settings.py

**Comment by caderitter** [comment]
Oh! Weird. I have it on my clone. I can add it back later today.

**Comment by riceluxs1t** [comment]
Most likely your settings file is included in your .gitignore file and contains some sensitive info (such as some secret key to a DB or something). If you are going to include the settings file, please make sure to put dummy keys instead and inform us directly of the secret keys

**Comment by riceluxs1t** [comment]
hey cade.

let me know if you get the settings file uploaded

**Comment by caderitter** [comment]
hey, it's uploaded now! key sent in email.
